### PR TITLE
Muisje/issue143

### PR DESCRIPTION
**Pull request by muisje**
Added functionality for handling multiple audio tracks.
Improved handling of skipping of subtitle generation.
Added class for dealing with language codes

### CODE REVIEW

**Comment by McCloudS** [comment]
Looks nice.  I’ll have to take a deeper look later.  Instead of extracting and saving the audio to the file system, you should be able to pass it straight to gen_subtitles and keep it in memory.  Would save file read/write times at the expense of memory usage.

I also need to figure out how to package it better.  Your current breakout of languages would require me to update the docker images (not a big deal) and launcher.py to download it.

**Comment by muisje** [comment]
Yeah i agree. Now extracts it to memory as bytes

**Comment by McCloudS** [comment]
Out of the gate, I get ```
  File "/Users/scott/Documents/whispertest/subgen/subgen.py", line 751, in get_audio_tracks
    except ffmpeg.Error as e:
           ^^^^^^^^^^^^
AttributeError: module 'ffmpeg' has no attribute 'Error'
```
ffmpeg-python doesn't raise 'Error'.

**Comment by McCloudS** [comment]
Looks great, I'll probably merge it later today with some small changes following.  I might use the opportunity to clean up the naming, kind of like you did, and expand some options.

**Pull request merged**
